name: droidenv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - torchaudio
  - torchvision
  - pytorch=1.10
  - cudatoolkit=11.3
  - tensorboard
  - scipy
  - opencv
  - tqdm
  - suitesparse
  - matplotlib
  - pyyaml
